### ISSUE TITLE
Provide printable A4/A3 models so that one can start understanding the design without a CNC

### ISSUE THREAD

**Issue by arthurlutz** [opensourcebeehives/Hive_Colorado_Top_Bar#3]
It would be nice if there were some easier way to start tinkering with the project than the CNC files. 

I see two possibilities : 
- printing an A4 or A3 version of the cut out so one can stick it to cardboard and build a small size prototype (or a full size prototype)
- printing a small scale replica with a 3d printer (flat print of pieces to be assembled).

**Comment by Amakaruk** [comment]
Here you go amigo: 
https://github.com/opensourcebeehives/Community_Projects

**Comment by arthurlutz** [comment]
Here is an A3 example I cooked up 
[hive_a3.pdf](https://github.com/opensourcebeehives/Hive_Colorado_Top_Bar/files/374341/hive_a3.pdf)

Or an SVG example : 
[hive_paper_A4.svg.zip](https://github.com/opensourcebeehives/Hive_Colorado_Top_Bar/files/374347/hive_paper_A4.svg.zip)

Or an STL (really approximate)
[hive.stl.zip](https://github.com/opensourcebeehives/Hive_Colorado_Top_Bar/files/374353/hive.stl.zip)

**Comment by Amakaruk** [comment]
Those are really cool - if you want to merge them with the community projects folder, i'll approve it. Thanks for contributing Arthur
